### ISSUE TITLE
下载的antdatacore项目中antdata.dbmodels生成mysql实体报错

### ISSUE THREAD

**Issue by Lu-Lucifer** [yuzd/AntData.ORM#4]
![o 1qe9v gi4gznr8 deifj](https://user-images.githubusercontent.com/29009277/53460137-0d4a4080-3a77-11e9-8197-b184ad82d740.png)

**Comment by yuzd** [comment]
tt模板错误报告不是很友好 采用vs插件来生成models
https://marketplace.visualstudio.com/items?itemName=nainaigu.AntDataVS
如果有错误 插件上的错误提示会更友好一点
