### ISSUE TITLE
.net core的版本不支持sharding吗？

### ISSUE THREAD

**Issue by NaturalDragon** [yuzd/AntData.ORM#5]
.net core分表会报错Please provide shard information.

**Comment by yuzd** [comment]
对的，netcore的版本 我没有移植这个功能，因为我发现这个功能很少实际会用到，你很需要这个功能？

**Comment by NaturalDragon** [comment]
最近在研究分库分表这块，对比了几个框架，你这个框架是最完善的！不知道你方便升级.netcore的sharding？

**Comment by yuzd** [comment]
ok 感谢支持 我搞下 尽量本周内

**Comment by NaturalDragon** [comment]
麻烦了，初次接触这个框架，不熟悉整体设计，改了小半天才把查询改了，你出手肯定是轻车熟路！

**Comment by yuzd** [comment]
v1.4.5 支持shardingdb 和 shardingtables。
还不支持db和tables 的sharding叠加

请查阅：https://github.com/yuzd/AntData.ORM/tree/netcore2/AntData/Test/TestSharding

**Comment by NaturalDragon** [comment]
感谢，辛苦了！

**Comment by NaturalDragon** [comment]
AntData.ORM-netcore2\AntData\AntData.ORM\DbEngine\Dao\sql\SqlBuilder.cs
批量插入方法BulkCopyCase  中集合dicValues没有判断key值重复，
 foreach (var tuple in tupleList)
                {
                    var key = shardingStrategy.ShardByDB ? tuple.Item1 : tuple.Item2;
                    if (dicValues.ContainsKey(key)) continue;
                    dicValues.Add(key, Tuple.Create(new List<string>(),new StatementParameterCollection()));
                }

**Comment by yuzd** [comment]
好的 晚点修复

**Comment by yuzd** [comment]
提交了一个新版本
